### ISSUE TITLE
Command 'Snippet:Find' resulted in error 

### ISSUE THREAD

**Issue by aspoofer0224** [mre/vscode-snippet#118]
Had the similar issues with https://github.com/mre/vscode-snippet/issues/19
but the problem still occurred even with the open folder.

**Comment by mre** [comment]
Since I can't dedicate much time to this project right now I've updated the `README.md` to note that I'm looking for maintainers. If anyone is interested please send me a message or reply here. Thanks! 😊

**Comment by TarunavBA** [comment]
I'm interested @mre

**Comment by mre** [comment]
Thanks, go for it. If you need anything let me know

**Comment by TarunavBA** [comment]
Ok sure!

**Comment by TarunavBA** [comment]
@aspoofer0224 Can you share a picture of the error?

**Comment by mre** [comment]
Closing this as I think it works as expected at the moment. Please reopen if that's not the case.
