### ISSUE TITLE
request: add to OpenVSX

### ISSUE THREAD

**Issue by robna** [mre/vscode-snippet#140]
Users who installed VSCode from the Arch or Manjaro repositories can't find the extension as the [OpenVSX](https://open-vsx.org) marketplace is used instead of the one from Microsoft. See alo here: https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

Currently vscode-snippet is not listed on OpenVSX. Users could workaround by downloading the package from the [MS marketplace](https://marketplace.visualstudio.com/items?itemName=vscode-snippet.Snippet) as a vsix file and then install from local.

**Comment by mre** [comment]
Hey @robna,
great idea. Just a little heads-up that this repo is currently looking for maintainers and there is very little activity at the moment. If you'd be interested in helping out, let me know. I'd be delighted to share the ownership.

**Comment by robna** [comment]
thx @mre, I could certainly look into how to get it on openVSX, but beyond that I doubt I could be helpful for maintaining, as I am no JavaScript dev.

**Comment by mre** [comment]
Thanks, that's fine. If you need any support or have questions, we can use this issue to align. 👍

**Comment by robna** [comment]
So I looked into it...
Open-VSX is now managed by the Eclipse foundation. Publishing an extension there requires creating an Eclipse account and signing the "[Eclipse Foundation Open VSX Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)". AFAICT, by doing so one confirms to have right to publish whatever you upload there. So unless you think it's a good idea for me as a non-contributor to take that role, I'd leave it to the more involved.

Another possibility: just don't publish it there now, until the extension has a new maintainer, who can then take it upon them if they want. People who are not able to install it, might find this issue here including the solution of downloading and installing manually, which works well.

**Comment by mre** [comment]
I don't have much bandwidth to work on this right now. Given the requirement to create a new Eclipse account, I think it's more than what I can commit to right now. We can keep this issue open in the hope that someone else might be interested in putting in the work. At least there is a workaround as you pointed out.

In the long run, finding a new maintainer would be the best thing, yes.

**Comment by jarusll** [comment]
Hey @mre, I have published on openvsx. I will break down the process.
Steps to publish on OVSX
- Signup on https://open-vsx.org/
- Generate a Personal Access Token on https://open-vsx.org/user-settings/tokens
- Create a namespace by `npx ovsx create-namespace <name> -p <personal-access-token>`
- Publish by `npx ovsx publish <packaged-extension-file> -p <personal-access-token>`

**Comment by mre** [comment]
Thanks @jarusll, I published snippet to open-vsx.org thanks to your instructions.
https://open-vsx.org/extension/vscode-snippet/snippet
Also published the latest version 0.9.0 to the Microsoft Marketplace. 🎉 
@robna fyi
