### ISSUE TITLE
Running the contributed command: 'snippet.find' failed.

### ISSUE THREAD

**Issue by pankaj-kvhld** [mre/vscode-snippet#19]
Snippet release v0.4.3
VS Code 1.33.1 

When I execute Snippet: Find, I get an error: Running the contributed command: 'snippet.find' failed.

How to resolve this issue?

**Comment by mre** [comment]
Hey @pankaj-kvhld,

just tested it on a vanilla visual studio code installation and it works for me.
Does it immediately print an error or only when hitting "enter" to find a snippet?
Do you run any special query?

**Comment by mre** [comment]
@pankaj-kvhld is this still an issue for you? It's tricky to debug from my side.

**Comment by pankaj-kvhld** [comment]
Apologies for late response. I realized that this only happens when no project folder is open. In an open project it works like a charm.
Is it supposed to behave like this? If yes, then I will close the issue. Thanks for making this lovely plugin.

**Comment by mre** [comment]
Ah that's a bug that we should fix.
Feel free to give it a shot if you like.
Otherwise I'll try to squeeze it in as soon as I find the time.

**Comment by pankaj-kvhld** [comment]
WOW, I have never contributed to open source, but want to. I don't think I know enough programming, but will give a shot. Thanks for the opportunity.

**Comment by mre** [comment]
We could actually keep that issue open for the time being so that we don't forget.
If you need any support with the implementation, just ask here. Me or somebody else (e.g. @GianOrtiz) will help you if we can.

As a first idea, the bug is located in https://github.com/mre/vscode-snippet/blob/master/src/extension.ts#L51 where we try to access the `languageId` even if we don't have a document.

**Comment by GianOrtiz** [comment]
Adding this https://github.com/mre/vscode-snippet/blob/master/src/extension.ts#L106-L110 to the find command should solve the problem, @pankaj-kvhld, @mre.

Or we could add a user preferred language config option, so whenever someone tries to use a command without an open editor the extension uses this language as default.

**Comment by mre** [comment]
Agree. As a third option, we could show another [input box](https://github.com/microsoft/vscode-extension-samples/tree/master/quickinput-sample) for the language.
I think I would go with the config option for now and maybe add support for the input box (if no default is set) later.
