### ISSUE TITLE
[Feature request] Visual Studio IDE's ToolBox alternative for VSCode

### ISSUE THREAD

**Issue by BachiMjavanadze** [mre/vscode-snippet#191]
`Visual Studio IDE` has a nice feature: ToolBox, witch gives you ability to save and use pieces of boilerplate code:

![tImg](https://user-images.githubusercontent.com/38082501/213792825-2ff83c48-3655-4e6d-94d4-31bcf1573709.gif)

Can't find a similar extension for `VSCode`. There many extensions with the similar name but they serve different job and are a bit complicated for me.

Can you add similar feature to your extention please?

Also add ability to group different commands in different folders like on the gif.

P.S. I' not talking about snippets which are built in `VSCode`, this is different.

**Comment by BachiMjavanadze** [comment]
Almost find it but it does not have foldering option and is no longer updated:
[https://marketplace.visualstudio.com/items?itemName=markvincze.code-fragments](url)

**Comment by mre** [comment]
That's a cool idea. The Code Fragments code is MIT licensed, so we could probably take over some of it and merge it with this project. @VladBrok, any thoughts?

**Comment by BachiMjavanadze** [comment]
> That's a cool idea. The Code Fragments code is MIT licensed, so we could probably take over some of it and merge it with this project. @VladBrok, any thoughts?

Great! looking forward to the results.

I think it woud be better if we have both ability: separate snippets by languages and have general ones. Main part is: ability to combain snippets in diifrent folders even in single language. i.e. for C# I will have diffrent groups for "console", "asp.net", "MAUI".

also, if you add `sync across devices' feature, it would be better.

**Comment by VladBrok** [comment]
This feature is very cool! We should definitely implement it

**Comment by BachiMjavanadze** [comment]
I think adding folding option per language will be tricky. maybe the easiest solution is to add subfolders and user will define folder for languages. i.e: `.Net` will be parent folder and subfolders will be: `console` and `WebApi`

**Comment by BachiMjavanadze** [comment]
I think if you mask underhood the tooltip like a regular snippet, they will be easily synchronized

**Comment by mre** [comment]
@BachiMjavanadze, we added support for snippets in #194.
All the functionality of Code Fragments (and more!) is integrated into Snippet now. 🎉 
This will be part of the next release.
Full credit goes to @VladBrok, who did an amazing job. Thanks a lot!

**Comment by VladBrok** [comment]
It is now available in the pre-release version. You can switch to the pre-release by clicking "Switch to Pre-Release Version"
![image](https://user-images.githubusercontent.com/79661007/216825251-527d57f1-d8cf-484f-825e-21943b796be3.png)

**Comment by BachiMjavanadze** [comment]
@VladBrok Excellent job!
If it is posible, please add ability to ad snippet by double click. Of course someone would prefer single click, so add in `settings.json` aditional option, like:

`"add-snippet-double-or-single-click": "single/double"`

**Comment by VladBrok** [comment]
No, I haven't added synchronization yet :(. But I think it could be added in the next release along with the ability to insert snippet by double click)

**Comment by BachiMjavanadze** [comment]
@VladBrok any news according to synchronization and double click?

**Comment by VladBrok** [comment]
Hi. I plan to publish a new relase soon (after #346 and #349). There will be snippet synchronization and a new settings option "insertWithDoubleClick".

**Comment by VladBrok** [comment]
@BachiMjavanadze new release is out! You can use the "insertWithDoubleClick" option in settings to insert snippets with a double click. Synchronisation can be done by clicking "Turn on Settings Sync" in vscode settings (if not already turned on).

**Comment by BachiMjavanadze** [comment]
@VladBrok May I give you an idea? This is a good [extention](https://github.com/easterapps/vscode-script-runner/issues), but author do not make any bug fixis may by you will clone repo and make new one. It is very useful for any languages/frameworks thad have no GUI in editor for creating script according to specifics

**Comment by VladBrok** [comment]
Thank you for the offer. The project looks interesting, but I have no spare time right now. I might look into it if I find some time
