### ISSUE TITLE
http_proxy_agent_1.HttpProxyAgent is not a constructor

### ISSUE THREAD

**Issue by romeroabelleira** [mre/vscode-snippet#24]
Trying to find a snippet behind a proxy fails with

> notificationsAlerts.ts:38 Error: http_proxy_agent_1.HttpProxyAgent is not a constructor
> 	at Object.<anonymous> (C:\Users\b275aj3\.vscode\extensions\vscode-snippet.snippet-0.6.1\out\query.js:80:25)
> 	at Generator.next (<anonymous>)
> 	at fulfilled (C:\Users\b275aj3\.vscode\extensions\vscode-snippet.snippet-0.6.1\out\query.js:4:58)

This seems to be related to the HttpProxyAgent call

https://github.com/mre/vscode-snippet/blob/8cb2f39a39a17e34e52e5165ce40ce2e3e3ae0fa/src/snippet.ts#L83

or the corresponding import

https://github.com/mre/vscode-snippet/blob/8cb2f39a39a17e34e52e5165ce40ce2e3e3ae0fa/src/snippet.ts#L6

Wild guess: It seems that HttpProxyAgent is regarded as type 'any' when I look at the file in vscode, so maybe the dependency wasn't loaded correctly.

Extension version: 0.6.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mre** [comment]
Hum... I recently refactored that part a bit.

This was the original version from the pull request [here](https://github.com/mre/vscode-snippet/pull/15/files):

```typescript
import * as HttpProxyAgent from 'http-proxy-agent' 
```

Looks like that's how I should do the import. My guess is that the `HttpProxyAgent` constructor is part of the `HttpProxyAgent` namespace, so it should be 

```typescript
let agent = new HttpProxyAgent.HttpProxyAgent(proxy) 
```

@kubac65 can you confirm?

If so, I'd revert the import back to the original version.

**Comment by mre** [comment]
This should be fixed now in the latest version (0.7.0). Can you try again?

**Comment by romeroabelleira** [comment]
Now it throws a 407 which is entirely possible, because I'm behind an authenticated corporate proxy. However, I have a custom `http.proxy` in my user settings which usually does the trick. Does this take the user-specified proxy into account?

Thank you for the time you've spent on this!

**Comment by mre** [comment]
I tested by adding the following `settings.json` and that worked:

```json
"http.proxy": "https://example.com"
```

So I'd say yes it should pick up your setting. 🤔

**Comment by kubac65** [comment]
If you need to use authenticated proxy use following format instead https://username:password@example.com

**Comment by mre** [comment]
Think we can close that. Thanks to @kubac65 for the answer!
