### ISSUE TITLE
Handle cht.sh 404 better

### ISSUE THREAD

**Issue by tennox** [mre/vscode-snippet#240]
Took me a while to figure this out (and still don't know why cht.sh is doing this) but for some queries [the second snippet returns 404](https://cht.sh/rust/flush+stdout/1) (but [the next ones work again](https://cht.sh/rust/flush+stdout/2)) :thinking: 

But this issue is about handling it better, as this extension shows this:

![Screenshot from 2023-03-03 16-35-46](https://user-images.githubusercontent.com/2084639/222766651-f054e42c-7569-41a0-bf54-9083add995dd.png)

Maybe a 404 could be shown as such?

**Comment by tennox** [comment]
Oh damn I just saw it returns HTTP 200:

```
$ http https://cht.sh/rust/flush+stdout/1
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 1611
Content-Type: text/plain; charset=utf-8
Date: Fri, 03 Mar 2023 15:57:31 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

/*
 * 404 NOT FOUND
 * 
 * Unknown cheat sheet. Please try to reformulate your query.
 * Query format:
 */

 /LANG/QUESTION

// Examples:
```

**Comment by tennox** [comment]
I opened a bug report on cheat.sh as that's kinda weird anyways:

https://github.com/chubin/cheat.sh/issues/377

**Comment by VladBrok** [comment]
Yeah, I think that this response from cht.sh looks fine:
```
/*
 * 404 NOT FOUND
 * 
 * Unknown cheat sheet. Please try to reformulate your query.
 * Query format:
 */

 /LANG/QUESTION

 // Examples:
 /python/read+json
```
But if the configuration option "verbose" is false, then the response looks weird. I think we can fix that
