### ISSUE TITLE
Make snippet title configurable

### ISSUE THREAD

**Issue by mre** [mre/vscode-snippet#28]
As soon as #27 gets merged, we could add a config option for changing the snippet title.
The default would be `[language] snippet query`, e.g. `[python] split string`, but we could make that adjustable.
For instance, users could decide to set it to `split string - python` or anything else.

To make this work, we document the variable names that are supported for the title string:

* `${language}` - the programming language 
* `${query}` - the snippet query (search text)
* `${index}` - the number of the snippet (e.g. 3 for the third answer)
* maybe more

**Comment by VladBrok** [comment]
I would like to work on this issue

**Comment by mre** [comment]
Thanks! I merged your pull request. This can be closed. 😊
