### ISSUE TITLE
How to quickly retrieve code snippets created by oneself using a keyboard?

### ISSUE THREAD

**Issue by Hoper-Q** [mre/vscode-snippet#377]
It seems that the current method is only hand points, how to get the code snippet of your choice through shortcut keys, and hope to appear in IntelliTips. Hope to answer that.

**Comment by VladBrok** [comment]
I think we can implement a snippet search similar to vscode's file search (Ctrl + P).

![image](https://github.com/mre/vscode-snippet/assets/79661007/55dd40c0-f509-4d25-96da-a93dd77afc46)

**Comment by mre** [comment]
We could combine it with the normal search. When a user searches for a snippet, we show the list of snippets below the search bar. On input, we filter for matching snippets. If the user hits enter, we trigger the normal search on cheat.sh. Just an idea. Might be that it's not a good fit and we want a separate search for snippets.

**Comment by mre** [comment]
We also have previous queries in the list below the search bar. If we want to go forward with this, I suggest to print `snippet` or `search` (or some other marker) before the name of the snippet to avoid confusion. 

Also, the question is if a user wants to search through the titles of the snippets only, or also their contents. The title would be easier. On top of that, users might be confused if a snippet shows up, where the preview doesn't contain the search term anyway, so maybe we can start by searching through the snippet titles only?

**Comment by Hoper-Q** [comment]
I think the method of searching by the title set by the user himself is a convenient setting, and it would be better if the&nbsp;snippet&nbsp;appeared in IntelliSense.Thank&nbsp;you&nbsp;for your&nbsp;reply&nbsp;to my queries.
&nbsp;


好人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matthias ***@***.***&gt;; 
发送时间: 2023年7月6日(星期四) 晚上10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mre/vscode-snippet] How to quickly retrieve code snippets created by oneself using a keyboard? (Issue #377)






我们在搜索栏下面的列表中也有以前的查询。如果我们想继续这样做，我建议打印小片或搜索（或其他标记）放在代码段的名称之前，以避免混淆。

另外，问题是用户是只想搜索片段的标题，还是也想搜索它们的内容。标题会比较容易。最重要的是，用户可能会感到困惑，如果一个片段显示，其中预览不包含搜索条件反正，所以也许我们可以开始通过搜索片段标题只？

—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.

**Comment by VladBrok** [comment]
> We also have previous queries in the list below the search bar. If we want to go forward with this, I suggest to print `snippet` or `search` (or some other marker) before the name of the snippet to avoid confusion.
> 
> Also, the question is if a user wants to search through the titles of the snippets only, or also their contents. The title would be easier. On top of that, users might be confused if a snippet shows up, where the preview doesn't contain the search term anyway, so maybe we can start by searching through the snippet titles only?

Agree, it's better to make searching through titles only for now

**Comment by VladBrok** [comment]
@Hoper-Q new release is out! Saved snippets are now displayed in IntelliSense
