### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by TurbooGhost** [mre/vscode-snippet#390]
I can't save any snippet. So when i click on add it shows me this error msg:
 <code>Error running command snippet.createFolder: command 'snippet.createFolder' not found. This is likely caused by the extension that contributes snippet.createFolder.</code>
 
I reset the extension setting. Disable it and then able it and it still the same error. 

I tried to remove so many vs code extension and it still getting the same error. 

<strong>What it cause this? What is the solution?</strong>

Thank you for the support

**Comment by VladBrok** [comment]
Hi! I'm investigating the issue.
Could you please tell:
1. what is your vscode version?
2. are you trying to create a folder like in the video (right click -> new folder), or some other way?

https://github.com/mre/vscode-snippet/assets/79661007/c38c6a95-ab19-4a6e-8e96-0d773773b94c

Could you also please try to enable dev tools (Ctrl + Shift + P -> toggle developer tools), open the console in dev tools and see if there are any errors during startup (Ctrl + Shift + P -> reload window) or while reproducing the folder creation issue?

**Comment by TurbooGhost** [comment]
Thank you for noticing my issue:

* My VS Code version is 1.80.1

* The video is not playing it is says "Video can't be played because the file is corrupt".

* This is the error in the console:

1. <code>ERR [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug</code>
2. <code>ERR [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass</code>
3. <code>ERR [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus</code>
4. <code>mainThreadExtensionService.ts:113 Activating extension 'vscode-snippet.snippet' failed: Cannot read properties of undefined (reading 'languages').</code>
5. <code>notificationsAlerts.ts:42 Error running command snippet.createFolder: command 'snippet.createFolder' not found. This is likely caused by the extension that contributes snippet.createFolder.</code>

* Am trying to select the snippet and then option to save the snippet, so what i do so is not saving. When i go to where i select the snippet and trying to add it just showing me this error msg: <code>Error running command snippet.createFolder: command 'snippet.createFolder' not found. This is likely caused by the extension that contributes snippet.createFolder.</code>

**Comment by VladBrok** [comment]
Thank you for providing additional details. The information from the console helped me to reproduce the issue. I've released the v1.1.1 version with the fix. Vscode should update it automatically and prompt for reload (after update, the version at the top of the extension should be 1.1.1 as shown below)
![image](https://github.com/mre/vscode-snippet/assets/79661007/6c76bc3b-26ed-4405-a554-10d60da05161)
Let me know if the issue is fixed

**Comment by TurbooGhost** [comment]
That's fantastic! It's working perfectly... I truly appreciate it!!!

**Comment by VladBrok** [comment]
Happy to help!
