### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mre** [mre/vscode-snippet#49]
Since this plugin is slowly gaining popularity, I'd like to avoid breaking it with a bad release.
Hence, I'd like to add some unit tests. I have no idea how to do that in the VSCode/Typescript ecosystem. 
Probably something like this from VSCodeVim: https://github.com/VSCodeVim/Vim/tree/master/test 
If anyone has an idea or can give me some pointers, I'd be very thankful.

**Comment by VladBrok** [comment]
I would like to work on this issue

**Comment by mre** [comment]
Thanks, that would be amazing. Go for it! 😊

**Comment by VladBrok** [comment]
Not sure, I think it's better to close this when more tests will be added
