### ISSUE TITLE
Provide live suggestions for user input

### ISSUE THREAD

**Issue by mre** [mre/vscode-snippet#5]
We should have an option for suggesting snippets while a user is typing a query.
Gitlens provides the same functionality.

See https://github.com/eamodio/vscode-gitlens

**Comment by GianOrtiz** [comment]
I would like to work on this one, but I have one question about this feature, this will display suggestions based on user previous queries or in the content displayed by cht.sh/:list?

**Comment by mre** [comment]
Both options are interesting.

I would start with suggestions from previous searches.
We can cache them somehow (e.g. in a `trie` if we want to be fancy) and then show a list of previous searches.

Once we have that nailed down, we could add live suggestions for keywords. I.e. if the user starts typing `sli` and we are currently in a Golang file, it could suggest `slice` and `sleep`.

As far as I can see, cheat.sh doesn't have support for suggestions yet, right @chubin? Shall I create an issue for that, or is it out of the scope for the project? Alternatively, we could query StackOverflow.

Thanks for raising those points @GianOrtiz. If you want, you could try adding suggestions based on previous searches for a start. 😊

**Comment by chubin** [comment]
Actually, we are already working on that and we are already quite far.
The idea is to analyze historical queries to the service and provide
possible suggestions basing on that.

We are experimenting with a naive prefix based approach (based on the historical queries solely),
and with a more sophisticated, HMM-based approach (based on the historical queries and the answers combined). The latter gives better results, but still not yet fully satisfying.

The interface will look like:
```
$ curl cheat.sh/python/create+empty?query=complete
create empty list
create empty array
create empty file
create empty dict
create empty set
```

**Comment by mre** [comment]
That's nice. Is there an issue to track so that we know when it's ready? Alternatively, just ping me and I'll update this issue here. Thanks for working on that; looks promising.

**Comment by chubin** [comment]
As soon as we have something to test, I will ping you here.

**Comment by GianOrtiz** [comment]
This issue will be closed and once the feature https://github.com/mre/vscode-snippet/issues/5#issuecomment-430407443 is ready to test another issue will be opened? Or we can continue the implementation of live suggestion using the user's past searches, saved in cache, @mre?

**Comment by mre** [comment]
> Or we can continue the implementation of live suggestion using the user's past searches, saved in cache, @mre?

Absolutely. We can just use this issue for that.
