### ISSUE TITLE
backup and local file

### ISSUE THREAD

**Issue by Doron-Shpigel** [mre/vscode-snippet#511]
Hi,
Is there a way to store the snippets I added to local file so I can backup them?

**Comment by VladBrok** [comment]
Hi, it's a very good question.

Vscode has a `state.vscdb` file. On my machine (Ubuntu Linux), it is located in `~/.config/Code/User/globalStorage/state.vscdb`.
To inspect the content of this file, you can use any tool that can open SQLite, for example, you can go to this website: https://inloop.github.io/sqlite-viewer/ and type the following command:
```sql
SELECT * FROM 'ItemTable' WHERE key like 'vscode-snippet.snippet'
```
then click "Execute".
![image](https://github.com/mre/vscode-snippet/assets/79661007/7ea17157-04f8-4c18-a898-7067cad38303)

You should find a single row with key `vscode-snippet.snippet` and value equal to json. This json has all snippets that you saved previously by using "save snippet" command.

So, you can backup this file in any way you want, and in case something bad happens, just restore the file.

**Comment by Doron-Shpigel** [comment]
thank you :)
