### ISSUE TITLE
Export, import

### ISSUE THREAD

**Issue by esshevelev** [mre/vscode-snippet#517]
Hello! Your app is incredibly convenient. However, I can't figure out how I can transfer (export, import) my snippets from one computer to another. Is it posible?

**Comment by VladBrok** [comment]
Hi! Currently, the synchronization of saved snippets across devices is possible via the vscode's default sync settings (Open vscode settings -> click on "Backup and Sync settings".)
![image](https://github.com/mre/vscode-snippet/assets/79661007/e79de801-d299-4cf2-b92a-e44333304553)
![image](https://github.com/mre/vscode-snippet/assets/79661007/76a6de0b-f53b-4e5d-b876-aea9659b1f2f)
