### ISSUE TITLE
Not all available languages are listed

### ISSUE THREAD

**Issue by ebeloded** [mre/vscode-snippet#54]
It seems that not all languages that are available from cht.sh, are available through the plugin.

For example, I was trying to look up a git command (https://cht.sh/git), but the list of languages doesn't list 'git'.

![image](https://user-images.githubusercontent.com/5859177/72400531-21288f00-377c-11ea-8036-86eb5695955a.png)

I understand that 'git' is not a language and not a file type, but it would be helpful to be able to look up git commands using the plugin.

PS. Thank you so much for the plugin!

**Comment by mre** [comment]
Ah right. That's a good idea. 😆 
I wonder if there is a way in VSCodes suggestion dropdown to allow any user input... 🤔

**Comment by mre** [comment]
Code is here BTW https://github.com/mre/vscode-snippet/blob/065e319b450d491c8ebfeff5ad0eb2a207453a94/src/config.ts#L8-L9

**Comment by mre** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/175809/72473789-bad95600-37e7-11ea-99b5-39867e468a10.png">
I've updated a new version (0.8.1) now that should fix this. Let me know how this is working for you @ebeloded. 😊

**Comment by ebeloded** [comment]
Yes, it is working perfectly!
