### ISSUE TITLE
Add own snippets or private snippets 

### ISSUE THREAD

**Issue by flight505** [mre/vscode-snippet#63]
An easy way of adding own snippets would be very nice to have. Adding directly to cheat.sh/ following some template for QC - or just private snippets.

**Comment by mre** [comment]
Hey @flight505,

could you give an example or two for a private snippet? Maybe it makes sense to contribute them to cheat.sh instead, but I there might also be good use-cases for private snippets that I'm not seeing at the moment.

**Comment by mre** [comment]
@flight505 any update on this?
