### ISSUE TITLE
Toggle the comments off/on for a single snippet

### ISSUE THREAD

**Issue by mre** [mre/vscode-snippet#7]
It would be nice to be able to toggle the comments off/on (for one snippet).
It is possible to fully disable comments completely, but it is not the same,
because usually, you want to get an answer with the comments, read them, and then remove them if you don't need them.

Not sure how to implement that yet, but pull requests and links to similar projects are welcome.
Further discussion: https://github.com/chubin/cheat.sh/pull/93

**Comment by chubin** [comment]
I believe @dbeniamine (the author of the Vim plugin) could help you with this issue, at least he could give you some info about his approach.

**Comment by mre** [comment]
> 2. I keep locally a query history, and give the possibility to replay the last query toggling comments

So smart! I'll go with this implementation. Thanks for the tip!

**Comment by dbeniamine** [comment]
your welcome ;)

**Comment by GianOrtiz** [comment]
I've develop a message box to ask if the user wants to display comments in a query if the query was already searched before by using the extension permanent cache.I think that it would be more useful if it use extensions temporary cache `requestCache`. I didn't understood if this was the original idea. What is your thougths?

**Comment by mre** [comment]
I think we could add another command "Snippet: Toggle comments", which would rerun the last query from the cache and set the `Q` parameter accordingly:

* With comments: `curl cht.sh/lua/table+keys`
* Without comments: `curl cht.sh/lua/table+keys?Q`

The setting should also be persistent, so if comments were toggled off, they would stay off for future queries.

**Comment by GianOrtiz** [comment]
Seems like a better idea, @mre. I will try to work on it, this command would be very useful for me.

**Comment by mre** [comment]
This was done in Version 0.5.1. Reference: https://github.com/mre/vscode-snippet/commit/4387c866c64c830f4a10cd6484b1a9ae8998d4a7
