### ISSUE TITLE
A little more documentation

### ISSUE THREAD

**Issue by ktw** [mre/vscode-snippet#72]
Is it possible to add a little more documentation?

I was creating a snippet for the launch.json file, but could not get the $1 and $2 variables working at all, so I ended up just using \t.

And how do we specify something like ${workspaceFolder} without the engine stripping the {} characters?

Example:
`"\t\"program\": \"${workspaceFolder}/bin/debug/netcoreapp3.1/compiled.dll\",",`

Result:
`"program": "workspaceFolder/bin/debug/netcoreapp3.1/compiled.dll",`

Desired result:
`"program": "${workspaceFolder}/bin/debug/netcoreapp3.1/compiled.dll",`

**Comment by mre** [comment]
Oh Hai,
I think you're looking for a different snippet plugin. Here is the [documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets) for that, which should also be more detailed. 😉 🍷

**Comment by ktw** [comment]
Oh... Embarrassing ... :-)

I just installed your extension and thought it was the one I was working with.
I didn't realize at all that there was something built into the editor.

But thank you very much for helping. :+1:

**Comment by mre** [comment]
> I just installed your extension and thought it was the one I was working with.

Now I wonder how many other people did the same. 😅 Impostor syndrome intensifying in 3...2...1...
