### ISSUE TITLE
Not work in remote container

### ISSUE THREAD

**Issue by dongdongbh** [mre/vscode-snippet#77]
I run my code inside the container on remote machine. I link remote container with vscode ssh, and I install Snippet extension inside the container, but when I use Snippet find, it takes long time to load, and then open a empty file, no result shows in the file. 

It seems there is a network error, but I'm sure my docker connect the network well. I can connnect the internet by the docker terminal inside the vscode terminal panel, and I also can install vscode extensions to the the container, so I'm not sure why this happens, is there any log files can I inspect the errors?

I also tested Snippet on the my local machine, and it works fine.

**Comment by mre** [comment]
Sorry for the late response @dongdongbh. Was quite busy with work.
I think this is related to the missing error handling when doing the web request with axios but I didn't have time to look into the problem any further. What I'm proposing is that we ask the community to help us during hacktoberfest. 
I'll create a new issue for that and we'll see how it goes. 🤞

**Comment by mre** [comment]
We got better error handling now thanks to @jarusll. Please check again and reopen the issue if it's not resolved. Thanks! 😃
