### ISSUE TITLE
Catch error when making axios request

### ISSUE THREAD

**Issue by mre** [mre/vscode-snippet#83]
The request handling of this VSCode plugin is not handling errors at the moment.
Here is the request code:
https://github.com/mre/vscode-snippet/blob/370d427158ad683590d8abc4cadd976d0c584041/src/snippet.ts#L99-L110

As you can see, we don't check for errors in line 106.
It would be great to catch errors there and show and error message to the user.
You can test this by going offline and searching for a snippet. In this case it should show an error message (and not silently fail).

Fixing this issue will probably help troubleshooting #77, so there is some real user value.

**Comment by brew-install-buzzwords** [comment]
Hi, I can take this issue if it's still available

**Comment by mre** [comment]
Sure. Assigning to you. Thanks! 😊

**Comment by bleek42** [comment]
Did this ever get solved..? If not, I can and will.

**Comment by mre** [comment]
Go for it. ❤️

**Comment by bleek42** [comment]
Didn't forget about this. Just been busy with two jobs and redoing my portfolio. I'll keep you updated.

**Comment by bleek42** [comment]
@mre ok to update dependencies, replace tslint (deprecated) with eslint, configure prettier while i'm at it, etc.? also, I think you need to add me as a contributor, still?

**Comment by mre** [comment]
Hey, that's all fine. Feel free to create a pull request for those changes. No need to be added as a contributor for that. This can happen later after a few pull requests. 🙂

**Comment by bleek42** [comment]
Ok, great! Yeah actually, that makes sense. I did not realize I could put in a PR, if not added as a contributor. I should have a PR in by Monday, 6/24.  👍

**Comment by mre** [comment]
This is fixed now thanks to @jarusll. 🥳

**Comment by bleek42** [comment]
@mre ugh my fault for flakin' on this... Had something workable too, almost but work & other duties have been very demanding. I'd like to see if I can solve another issue, now that my time is freed up a bit recently. Thanks @jarusll for picking this up.
