### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by mre** [mre/vscode-snippet#9]
It's nice to update the package dependencies from time to time.

What would have to be done:

1. Update the `package.json` using [npm update](https://docs.npmjs.com/cli/update)
2. Test if the plugin still works by [installing the development build](https://code.visualstudio.com/docs/extensions/developing-extensions) and testing it.
3. Create a pull request with the updated `package.json` and `package.lock`.

This ticket is ideal for people who are interested in getting started with VSCode plugin development.

**Comment by daviddeejjames** [comment]
Happy to take this one :)
